FROM harbor.loongnix.cn/mips/alpine:3.11.11

LABEL maintainer="zhaixiaojuan <zhaixiaojuan@loongson.cn>"

COPY mc /usr/bin/
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

RUN  \
     apk add --no-cache ca-certificates && \
     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

ENTRYPOINT ["mc"]
